version: '3.6'

services:
  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app/:/home/app/
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    env_file: .env.dev
    expose:
      - 5432